apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ required "Missing value FDK_INGRESSNAME" .Values.FDK_INGRESSNAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: {{ required "Missing value FDK_INGRESS_IP_NAME" .Values.FDK_INGRESS_IP_NAME }}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ required "Missing value FDK_ALL_CERT_NAMES" .Values.FDK_ALL_CERT_NAMES }}
spec:
  {}
