apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required "Missing value FDK_INGRESSNAME" .Values.FDK_INGRESSNAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: {{ required "Missing value FDK_INGRESS_IP_NAME" .Values.FDK_INGRESS_IP_NAME }}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ required "Missing value FDK_ALL_CERT_NAMES" .Values.FDK_ALL_CERT_NAMES }}
spec:
  rules:
    - host: {{ required "Missing value HOSTNAME_REGISTRATION" .Values.HOSTNAME_REGISTRATION }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-registration
                port:
                  number: 8080
    - host: {{ required "Missing HOSTNAME_WWW" .Values.HOSTNAME_WWW }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-search
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_NAP" .Values.HOSTNAME_NAP }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-search
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_CONCEPT_CATALOGUE_GUI" .Values.HOSTNAME_CONCEPT_CATALOGUE_GUI }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: concept-catalogue-gui
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_CONCEPT_CATALOGUE" .Values.HOSTNAME_CONCEPT_CATALOGUE }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: concept-catalog
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_SSO" .Values.HOSTNAME_SSO }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: sso
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_ADMIN" .Values.HOSTNAME_ADMIN }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-admin-gui
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_ADMIN_API" .Values.HOSTNAME_ADMIN_API }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-harvest-admin
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_BROKER_ADMIN" .Values.HOSTNAME_BROKER_ADMIN }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: rabbitmq
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_PORTAL" .Values.HOSTNAME_PORTAL }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-search
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_ORGANIZATION_CATALOGUE" .Values.HOSTNAME_ORGANIZATION_CATALOGUE }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: organization-catalogue
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_PROTOCOL" .Values.HOSTNAME_PROTOCOL }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-records
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_TRANSPORTPORTAL" .Values.HOSTNAME_TRANSPORTPORTAL }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-search
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_DATASERVICE_PUBLISHER" .Values.HOSTNAME_DATASERVICE_PUBLISHER }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: dataservice-publisher
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_DATASERVICE_HARVESTER" .Values.HOSTNAME_DATASERVICE_HARVESTER }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-dataservice-harvester
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_SEARCH" .Values.HOSTNAME_SEARCH }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-fulltext-search
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_DATASET_HARVESTER" .Values.HOSTNAME_DATASET_HARVESTER }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-dataset-harvester
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_DATASERVICE_CATALOG" .Values.HOSTNAME_DATASERVICE_CATALOG }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-dataservices
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_TERMS_AND_CONDITIONS" .Values.HOSTNAME_TERMS_AND_CONDITIONS }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: terms-and-conditions
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_ORGANIZATION_BFF" .Values.HOSTNAME_ORGANIZATION_BFF }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-organization-bff
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_REPORTS_BFF" .Values.HOSTNAME_REPORTS_BFF }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-reports-bff
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_DATASET_CATALOG" .Values.HOSTNAME_DATASET_CATALOG }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: dataset-catalog
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_METADATA_QUALITY_SERVICE" .Values.HOSTNAME_METADATA_QUALITY_SERVICE }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-metadata-quality-service
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_INFORMATIONMODEL_HARVESTER" .Values.HOSTNAME_INFORMATIONMODEL_HARVESTER }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-informationmodel-harvester
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_DCAT_VALIDATOR" .Values.HOSTNAME_DCAT_VALIDATOR }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: dcat-ap-no-validator-service
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_FDK_PUBLISHERS" .Values.HOSTNAME_FDK_PUBLISHERS }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-publishers
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_CONCEPT_HARVESTER" .Values.HOSTNAME_CONCEPT_HARVESTER }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-concept-harvester
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_FDK_COMMUNITY" .Values.HOSTNAME_FDK_COMMUNITY }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-community
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_SPARQL_SERVICE" .Values.HOSTNAME_SPARQL_SERVICE }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-nginx-sparql
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_CONCEPT_CATALOG" .Values.HOSTNAME_CONCEPT_CATALOG }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: concept-catalog
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_CATALOG_COMMENTS" .Values.HOSTNAME_CATALOG_COMMENTS }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalog-comments-service
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_FDK_CMS_SERVICE" .Values.HOSTNAME_FDK_CMS_SERVICE }}
      http:
        paths:
          - path: /admin/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-cms-service-admin
                port:
                  number: 8080
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-cms-service
                port:
                  number: 8080
    - host: {{ required "Missing value HOSTNAME_FDK_MONITORING_SERVICES_GRAFANA" .Values.HOSTNAME_FDK_MONITORING_SERVICES_GRAFANA }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: fdk-monitoring-services-grafana
                port: 3000