name: Deploy to demo (ipv4 & ipv6)

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-demo-ipv4:
    name: Deploy ingress(ipv4) to demo environment on merge to main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@adaa40c0c581f276132199d4cf60afa07ce60eac  # v1.2.4
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DIGDIR_FDK_INGRESS_DEMO_IPV4 }}

      - name: Apply Helm template
        run: |
          helm template -f ${{ steps.write_file.outputs.filePath }} \
          ./helm-sources-demo/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Auth gcloud CLI for deploy
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed  # v2.1.13
        with:
          credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}

      - name: Get credentials
        uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395  # v3.0.0
        with:
          cluster_name: digdir-fdk-dev
          location: europe-north1-a

      - name: Deploy to GCP & check status
        run: |
          kubectl apply -f ./kubectlapply.yaml --force

      - name: Notify slack
        uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e  # v3.19.0
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: ingress(ipv4) | Environment: demo'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  deploy-demo-ipv6:
    name: Deploy ingress(ipv6) to demo environment on merge to main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@adaa40c0c581f276132199d4cf60afa07ce60eac  # v1.2.4
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DIGDIR_FDK_INGRESS_DEMO_IPV6 }}

      - name: Apply Helm template
        run: |
          helm template -f ${{ steps.write_file.outputs.filePath }} \
          ./helm-sources-demo/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Auth gcloud CLI for deploy
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed  # v2.1.13
        with:
          credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}

      - name: Get credentials
        uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395  # v3.0.0
        with:
          cluster_name: digdir-fdk-dev
          location: europe-north1-a

      - name: Deploy to GCP & check status
        run: |
          kubectl apply -f ./kubectlapply.yaml --force

      - name: Notify slack
        uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e  # v3.19.0
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: ingress(ipv6) | Environment: demo'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
