name: Deploy to staging (ipv4 & ipv6)

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-staging-ipv4:
    name: Deploy ingress(ipv4) to staging environment when pull request is created
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@master
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DIGDIR_FDK_INGRESS_STAGING_IPV4 }}

      - name: Apply Helm template
        run: |
          helm template -f ${{ steps.write_file.outputs.filePath }} \
          ./helm-chart-staging/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Setup gcloud CLI for deploy
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
          export_default_credentials: true

      - name: Deploy to GCP & check status
        run: |
          gcloud container clusters get-credentials digdir-fdk-dev --region europe-north1-a --project digdir-fdk-dev
          kubectl apply -f ./kubectlapply.yaml --force
          if ! kubectl --namespace=staging rollout status ingress ingress-staging-v4; then
            kubectl --namespace=staging rollout undo ingess ingress-staging-v4
            kubectl --namespace=staging rollout status ingress ingress-staging-v4
            exit 1
          fi

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Application: ingress(ipv4) | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  deploy-staging-ipv6:
    name: Deploy ingress(ipv6) to staging environment when pull request is created
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@master
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DIGDIR_FDK_INGRESS_STAGING_IPV6 }}

      - name: Apply Helm template
        run: |
          helm template -f ${{ steps.write_file.outputs.filePath }} \
          ./helm-chart-staging/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Setup gcloud CLI for deploy
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
          export_default_credentials: true

      - name: Deploy to GCP & check status
        run: |
          gcloud container clusters get-credentials digdir-fdk-dev --region europe-north1-a --project digdir-fdk-dev
          kubectl apply -f ./kubectlapply.yaml --force
          if ! kubectl --namespace=staging rollout status ingress ingress-staging-v6; then
            kubectl --namespace=staging rollout undo ingess ingress-staging-v6
            kubectl --namespace=staging rollout status ingress ingress-staging-v6
            exit 1
          fi

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Application: ingress(ipv6) | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
