name: Deploy to ut1

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-ut1:
    name: Deploy ingress to ut1 environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.FDK_INGRESS_UT1 }}

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk-ingress https://informasjonsforvaltning.github.io/fdk-ingress-config/
            helm fetch --untar --untardir ./helm fdk-ingress/ingress
            helm template -f ${{ steps.write_file.outputs.filePath }} ./helm/ingress/ > ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.FDK_DEV_AUTODEPLOY }}
          project_id: fdk-dev
          location_zone: europe-north1-a
          cluster_name: fdk-dev

      - name: Deploy to staging-ut1
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"