name: Deploy to staging (ipv4 & ipv6)

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-staging-ipv4:
    name: Deploy ingress(ipv4) to staging environment when pull request is created
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c  # v1.2.4
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DIGDIR_FDK_INGRESS_STAGING_IPV4 }}

      - name: Apply Helm template
        run: |
          helm template -f ${{ steps.write_file.outputs.filePath }} \
          ./helm-sources-staging/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Auth gcloud CLI for deploy
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093  # v3.0.0
        with:
          credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}

      - name: Get credentials
        uses: google-github-actions/get-gke-credentials@64bc7249bbcf78056bb92f14d3cedc2da193946c  # v2.3.5
        with:
          cluster_name: digdir-fdk-dev
          location: europe-north1-a

      - name: Deploy to GCP & check status
        run: |
          kubectl apply -f ./kubectlapply.yaml --force

      - name: Notify slack
        uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e  # v3.19.0
        with:
          status: ${{ job.status }}
          author_name: 'Application: ingress(ipv4) | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  deploy-staging-ipv6:
    name: Deploy ingress(ipv6) to staging environment when pull request is created
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c  # v1.2.4
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DIGDIR_FDK_INGRESS_STAGING_IPV6 }}

      - name: Apply Helm template
        run: |
          helm template -f ${{ steps.write_file.outputs.filePath }} \
          ./helm-sources-staging/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Auth gcloud CLI for deploy
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093  # v3.0.0
        with:
          credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}

      - name: Get credentials
        uses: google-github-actions/get-gke-credentials@64bc7249bbcf78056bb92f14d3cedc2da193946c  # v2.3.5
        with:
          cluster_name: digdir-fdk-dev
          location: europe-north1-a

      - name: Deploy to GCP & check status
        run: |
          kubectl apply -f ./kubectlapply.yaml --force

      - name: Notify slack
        uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e  # v3.19.0
        with:
          status: ${{ job.status }}
          author_name: 'Application: ingress(ipv6) | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
